import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./Components/Navbar/Nav";
import { v4 as uuidv4 } from "uuid";
import ExcludedNav from "./ExcludedNav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./Components/Providers/Providers";

const inter = Inter({ subsets: ["latin"] });

// Static Data
export const dashboardBoxes = [
	{
		img: "Coupon",
		text: "60 % off",
		link: "",
	},
	{ img: "Steering", text: "Car Interior", link: "" },
	{
		img: "exterior",
		text: "Car Exterior",
		link: "",
	},
	{
		img: "perfume",
		text: "Accessories",
		link: "",
	},
];

export const dashboardTrendingCards = [
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
];

export const CatalogueData = [
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
	{
		uuid: uuidv4(),
		img: "cardImg",
		title: "Rear Bumper Model- RW",
		price: "19990",
		currentCart: 0,
	},
];

export const metadata = {
	title: "Saak",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="bg-[#393037]">
			<body className={inter.className}>
				<Providers>
					<ToastContainer
						position="top-center"
						autoClose={1500}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme="dark"
					/>
					<ExcludedNav>
						<Nav />
					</ExcludedNav>
					{children}
				</Providers>
			</body>
		</html>
	);
}
